name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: 
          - alpine
          - debian

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image (${{ matrix.flavor }})
        run: |
          docker build . --file Dockerfile.${{ matrix.flavor }} --tag cs-firewall-bouncer:${{ matrix.flavor }}-$(date +%s)
